[package]
name = "wordpress-scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true

[dependencies]
rocket = "0.5.0-rc.2"
reqwest = { version = "0.11.11", features = ["json"] }
tokio = { version = "1.21.1", features = ["full"] }
futures = "0.3.24"
openssl = { version = "*", features = ["vendored"] }
