[package]
name = "m183-totp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true

[dependencies]
rocket = { version  = "0.5.0-rc.2", features = ["secrets"] }
tokio = { version = "1.21.1", features = ["full"] }
futures = "0.3.24"
openssl = { version = "*", features = ["vendored"] }
tera = "1"
serde_json = "1.0.85"


[dependencies.sqlx]
version = "0.6.0"
features = ["runtime-tokio-rustls"]

[dependencies.rocket_auth]
git = "https://github.com/3n3a/rocket_auth"
branch = "master"
features = ["sqlx-sqlite"]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]
